language: node_js
node_js: 
    - '9.1.0'
cache:
  directories:
    - node_modules
 
 
# S: Build Lifecycle
install:
  - npm install

before_script:
 
# 无其他依赖项所以执行npm run build 构建就行了
script:
  - npm run build
 
after_script:
  - cp favicon.ico docs/favicon.ico
  - cd ./dist
  - git init
  - git config user.name "xubowenjx"
  - git config user.email "286129936@qq.com"
  - git add -A
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}
# E: Build LifeCycle
 
#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master
env:
 global:
   - GH_REF:  github.com/xubowenjx/vuepress-demo.git